if(WIN32)
	set(LIBHTTPROUTE_BASE_DIR "${PROJECT_SOURCE_DIR}/../libhttproute")
	find_path(
		LIBHTTPROUTE_INCLUDE_DIRS
		NAMES libhttproute/defines.h
		HINTS "${LIBHTTPROUTE_BASE_DIR}"
	)
	find_library(
		LIBHTTPROUTE_LIBRARY_DEBUG
		NAMES libhttproute.lib
		HINTS "${LIBHTTPROUTE_BASE_DIR}/build/Debug"
	)
	find_library(
		LIBHTTPROUTE_LIBRARY_RELEASE
		NAMES libhttproute.lib
		HINTS "${LIBHTTPROUTE_BASE_DIR}/build/Release"
	)
	if(LIBHTTPROUTE_INCLUDE_DIRS AND LIBHTTPROUTE_LIBRARY_DEBUG AND LIBHTTPROUTE_LIBRARY_RELEASE)
		set(LIBHTTPROUTE_FOUND TRUE)
		set(
			LIBHTTPROUTE_LIBRARY
			debug ${LIBHTTPROUTE_LIBRARY_DEBUG}
			optimized ${LIBHTTPROUTE_LIBRARY_RELEASE}
		)
	endif()
endif(WIN32)